#!/sbin/busybox sh

if [ "a$2" != "a" ];then
  bln_effect=$2

  case "${bln_effect}" in
    0) 
      echo 0 > /sys/class/misc/backlightnotification/breathing_enabled
      echo 0 > /sys/class/misc/backlightnotification/blinking_enabled
      ;;
    1)
      echo 1 > /sys/class/misc/backlightnotification/breathing_enabled
      echo 2500 3300 50 100 500 > /sys/class/misc/notification/breathing_config
      ;;
    2)
      echo 1 > /sys/class/misc/backlightnotification/blinking_enabled
      echo 1000 1000 > /sys/class/misc/backlightnotification/blinking_config
      ;;
  esac;
fi

echo ${bln_effect}
